'use client';
import type { Metadata } from 'next'

import { ChakraProvider } from "@chakra-ui/react"
import WalletContextProvider from './components/WalletContextProvider'

import { extendTheme } from "@chakra-ui/react"

const colors = {
  background: "#1F1F1F",
  accent: "#833BBE",
  bodyText: "rgba(255, 255, 255, 0.75)",
}

const theme = extendTheme({ colors })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>
          <WalletContextProvider>
            {children}
          </WalletContextProvider>
        </ChakraProvider>
      </body>
    </html>
  )
}
